language: php

sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
   fast_finish: true

git:
  depth: 1

cache:
  apt: true
  timeout: 604800
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - PHALCON_VERSION=v3.3.2 #TODO change this version to 4.0 later

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;

install:
  - bash tests/_ci/install_phalcon.sh
  - cd $TRAVIS_BUILD_DIR
  - travis_retry composer install --prefer-dist --no-interaction

before_script:

script:
  - vendor/bin/phpcs
  - vendor/bin/codecept build
  - vendor/bin/codecept run unit -v
  - vendor/bin/phpstan analyse -l max -c phpstan.neon src -v

notifications:
  email:
    on_success: never
    on_failure: never
