language: php

sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
   fast_finish: true

git:
  depth: 1

cache:
  apt: true
  timeout: 604800
  directories:
    - vendor
    - $HOME/.composer/cache



before_install:
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;

install:
  - travis_retry composer install --prefer-dist --no-interaction

before_script:

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit tests -v
  - vendor/bin/phpstan analyse -l max -c phpstan.neon src -v

notifications:
  email: false
